import sbt.Keys.updateOptions
import sbt._

lazy val commonSettings = Seq(
	name := "slinky-atlaskit",
  version := "1.0",
  scalaVersion := "2.12.8",
  organization := "com.harana",
	target := file(baseDirectory.value + "/../target") / name.value,
  resolvers ++= Seq(Resolver.sonatypeRepo("releases"),
	                  Resolver.sonatypeRepo("snapshots"),
										"Typed" at "https://dl.bintray.com/oyvindberg/ScalablyTyped"),
  updateOptions := updateOptions.value.withCachedResolution(true),
	addCompilerPlugin("org.scalamacros" % "paradise" % "2.1.1" cross CrossVersion.full),
	javacOptions ++= Seq()
)

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

lazy val js = (project in file("js"))
  .settings(
	commonSettings,
		scalaJSUseMainModuleInitializer := true,
	  jsEnv := new org.scalajs.jsenv.jsdomnodejs.JSDOMNodeJSEnv(),
		requireJsDomEnv in Test := true,
		skip in packageJSDependencies := false,
    emitSourceMaps := false,
		useYarn := true,
		addCommandAlias("start", ";compile;fastOptJS::startWebpackDevServer;~fastOptJS"),
		addCommandAlias("stop", "fastOptJS::stopWebpackDevServer"),
		version in webpack := "4.28.3",
		version in startWebpackDevServer := "3.1.4",
		scalaJSOptimizerOptions in fastOptJS ~= { _.withDisableOptimizer(true) },
	  scalacOptions += "-P:scalajs:sjsDefinedByDefault",
		webpackDevServerExtraArgs in fastOptJS := Seq("--inline", "--hot"),
		webpackBundlingMode in fastOptJS := BundlingMode.LibraryOnly(),
		webpackBundlingMode in fullOptJS := BundlingMode.Application,
	  libraryDependencies ++= Seq(
			"me.shadaj"                               %%%   "slinky-core"               					% "0.5.2",
			"me.shadaj"                               %%%   "slinky-web"               						% "0.5.2",
			"org.scalablytyped"												%%% 	"csstype"						 									% "2.6.2-522be0",
			"org.scalablytyped"												%%% 	"react"						 										% "16.8-dt-20190220Z-16f783",
			"org.scalablytyped"												%%% 	"std"						 											% "3.3-0ec965"
		),
		dependencyOverrides ++= Seq(
			"org.scala-js" 															% 	"sbt-scalajs" 												% "0.6.26"
		),
	  npmDependencies in Compile ++= Seq(
			"react"                                   -> "16.7.0",
			"react-dom"                               -> "16.7.0",
			"@atlaskit/avatar"                        -> "15.0.1",
			"@atlaskit/badge"                         -> "10.0.0",
			"@atlaskit/banner"                        -> "8.0.1",
			"@atlaskit/blanket"                       -> "8.0.1",
			"@atlaskit/breadcrumbs"                   -> "7.0.1",
			"@atlaskit/button-group"                  -> "1.5.4",
			"@atlaskit/button"                        -> "11.0.3",
			"@atlaskit/calendar"                      -> "7.0.20",
			"@atlaskit/comment"                       -> "7.0.3",
			"@atlaskit/css-reset"                     -> "3.0.6",
			"@atlaskit/dropdown-menu"                 -> "7.0.2",
			"@atlaskit/droplist-group"                -> "1.0.6",
			"@atlaskit/droplist-item"                 -> "2.0.8",
			"@atlaskit/droplist-trigger"              -> "1.1.4",
			"@atlaskit/droplist"                      -> "8.0.1",
			"@atlaskit/editor-bitbucket"              -> "4.12.9",
			"@atlaskit/editor-core"                   -> "106.2.0",
			"@atlaskit/editor-cq"                     -> "6.14.1",
			"@atlaskit/editor-hipchat"                -> "5.4.4",
			"@atlaskit/editor-jira"                   -> "22.11.12",
			"@atlaskit/editor-shared-styles"          -> "1.0.2",
			"@atlaskit/emoji"                         -> "58.1.1",
			"@atlaskit/field-base"                    -> "12.0.0",
			"@atlaskit/field-radio-group"             -> "5.0.1",
			"@atlaskit/field-text"                    -> "8.0.1",
			"@atlaskit/flag"                          -> "10.0.1",
			"@atlaskit/icon"                          -> "16.0.5",
			"@atlaskit/inline-dialog"                 -> "10.0.1",
			"@atlaskit/inline-edit"                   -> "8.0.1",
			"@atlaskit/inline-message"                -> "8.0.1",
			"@atlaskit/input"                         -> "5.0.0",
			"@atlaskit/layer"                         -> "6.0.0",
			"@atlaskit/lozenge"                       -> "7.0.0",
			"@atlaskit/mention"                       -> "17.2.0",
			"@atlaskit/navigation"                    -> "34.0.1",
			"@atlaskit/modal-dialog"                  -> "8.0.3",
			"@atlaskit/page"                          -> "9.0.1",
			"@atlaskit/profilecard"                   -> "8.0.2",
			"@atlaskit/single-select"                 -> "7.0.1",
			"@atlaskit/spinner"                       -> "10.0.1",
			"@atlaskit/tag-group"                     -> "7.0.0",
			"@atlaskit/tag"                           -> "7.0.0",
			"@atlaskit/toggle"                        -> "6.0.2",
			"@atlaskit/tooltip"                       -> "13.0.1",
			"@atlaskit/util-common"                   -> "1.5.2",
			"@atlaskit/util-readme"                   -> "3.6.6",
			"@atlaskit/tabs"                          -> "9.0.0",
			"@atlaskit/multi-select"                  -> "12.0.1",
			"@atlaskit/logo"                          -> "10.0.2",
			"@atlaskit/reduced-ui-pack"               -> "10.5.5",
			"@atlaskit/media-core"                    -> "29.0.1",
			"@atlaskit/media-card"                    -> "57.0.2",
			"@atlaskit/app-switcher"                  -> "9.1.0",
			"@atlaskit/reactions"                     -> "16.1.1",
			"@atlaskit/media-filmstrip"               -> "30.0.1",
			"@atlaskit/pagination"                    -> "10.0.1",
			"@atlaskit/renderer"                      -> "44.0.3",
			"@atlaskit/dynamic-table"                 -> "11.0.1",
			"@atlaskit/media-viewer"                  -> "39.0.1",
			"@atlaskit/media-avatar-picker"           -> "17.0.1",
			"@atlaskit/media-editor"                  -> "31.0.1",
			"@atlaskit/code"                          -> "9.0.0",
			"@atlaskit/header"                        -> "2.0.0",
			"@atlaskit/media-image"                   -> "10.0.1",
			"@atlaskit/drag-and-drop"           			-> "4.5.4",
			"@atlaskit/field-range"                   -> "6.0.1",
			"@atlaskit/task-decision"                 -> "13.1.1",
			"@atlaskit/item"                          -> "9.0.0",
			"@atlaskit/util-service-support"          -> "4.0.1",
			"@atlaskit/lerna"                         -> "2.0.0",
			"@atlaskit/atlaskit-registry"             -> "1.0.0",
			"@atlaskit/theme"                         -> "8.1.1",
			"@atlaskit/activity"                      -> "1.0.3",
			"@atlaskit/xflow"                         -> "6.25.1",
			"@atlaskit/privacy-safe"                  -> "1.0.0",
			"@atlaskit/size-detector"                 -> "7.0.0",
			"@atlaskit/layer-manager"                 -> "6.0.1",
			"@atlaskit/docs"                          -> "7.0.1",
			"@atlaskit/checkbox"                      -> "6.0.1",
			"@atlaskit/spotlight"                     -> "1.1.2",
			"@atlaskit/progress-indicator"            -> "6.0.1",
			"@atlaskit/editor-common"                 -> "35.0.3",
			"@atlaskit/polyfills"                     -> "3.0.5",
			"@atlaskit/field-text-area"               -> "5.0.1",
			"@atlaskit/page-header"                   -> "7.0.2",
			"@atlaskit/onboarding"                    -> "7.0.1",
			"@atlaskit/datetime-picker"               -> "7.0.1",
			"@atlaskit/empty-state"                   -> "4.0.1",
			"@atlaskit/editor-bitbucket-transformer"  -> "5.0.1",
			"@atlaskit/editor-jira-transformer"       -> "6.0.1",
			"@atlaskit/editor-cq-transformer"         -> "2.1.8",
			"@atlaskit/editor-json-transformer"       -> "5.0.1",
			"@atlaskit/conversation"                  -> "14.0.1",
			"@atlaskit/progress-tracker"              -> "5.0.0",
			"@atlaskit/editor-confluence-transformer" -> "6.0.1",
			"@atlaskit/table-tree"                    -> "6.0.2",
			"@atlaskit/media-picker"                  -> "37.0.1",
			"@atlaskit/select"                        -> "8.0.3",
			"@atlaskit/editor-markdown-transformer"   -> "3.0.1",
			"@atlaskit/notification-indicator"        -> "5.1.1",
			"@atlaskit/notification-log-client"       -> "4.0.1",
			"@atlaskit/media-store"                   -> "11.0.1",
			"@atlaskit/global-search"                 -> "6.0.1",
			"@atlaskit/media-ui"                      -> "10.0.1",
			"@atlaskit/editor-mobile-bridge"          -> "7.1.3",
			"@atlaskit/editor-wikimarkup-transformer" -> "4.0.1",
			"@atlaskit/smart-card"                    -> "10.1.1",
			"@atlaskit/nps"                           -> "5.0.2",
			"@atlaskit/pubsub"                        -> "4.0.1",
			"@atlaskit/quick-search"                  -> "6.0.1",
			"@atlaskit/navigation-next"               -> "5.0.1",
			"@atlaskit/form"                          -> "5.2.4",
			"@atlaskit/global-navigation"             -> "6.1.4",
			"@atlaskit/tree"                          -> "5.0.1",
			"@atlaskit/drawer"                        -> "3.0.1",
			"@atlaskit/avatar-group"                  -> "3.0.1",
			"@atlaskit/adf-utils"                     -> "6.0.0",
			"@atlaskit/section-message"               -> "2.0.1",
			"@atlaskit/popper"                        -> "0.4.1",
			"@atlaskit/portal"                        -> "0.2.1",
			"@atlaskit/date"                          -> "0.6.1",
			"@atlaskit/radio"                         -> "0.5.1",
			"@atlaskit/outbound-auth-flow-client"     -> "2.0.1",
			"@atlaskit/feature-flag-client"           -> "2.1.1",
			"@atlaskit/feedback-collector"            -> "3.0.2",
			"@atlaskit/status"                        -> "0.7.1",
			"@atlaskit/i18n-tools"                    -> "0.5.0",
			"@atlaskit/mobile-header"                 -> "2.1.0",
			"@atlaskit/panel"                         -> "0.1.1",
			"@atlaskit/icon-file-type"                -> "3.0.5",
			"@atlaskit/icon-object"                   -> "3.0.5",
			"@atlaskit/user-picker"                   -> "3.1.0",
			"@atlaskit/embedded-document"             -> "0.4.1",
			"@atlaskit/focused-task-close-account"    -> "0.9.0",
			"@atlaskit/color-picker"                  -> "0.4.1",
			"@atlaskit/range"                         -> "0.2.0",
			"@atlaskit/textarea"                      -> "0.4.0",
			"@atlaskit/textfield"                     -> "0.4.0",
			"@atlaskit/type-helpers"                  -> "3.0.2",
			"@atlaskit/branch-installer"              -> "0.0.8",
			"@atlaskit/adf-schema"                    -> "2.0.1",
			"@atlaskit/share"                         -> "0.2.4",
			"@atlaskit/icon-priority"                 -> "3.0.2",
			"@atlaskit/updater-cli"                   -> "2.0.1",
			"@atlaskit/atlassian-switcher"            -> "0.3.0",
			"@atlaskit/width-detector"                -> "0.3.1",
			"@atlaskit/nachos-textfield"              -> "0.0.5"
		),
		npmDevDependencies in Compile ++= Seq(
			"url-loader"                              -> "0.6.2",
			"css-loader"                              -> "0.28.7",
			"html-webpack-plugin"                     -> "3.2.0",
			"copy-webpack-plugin" 										-> "4.5.1",
			"static-site-generator-webpack-plugin" 		-> "3.4.1"
		)
  )
  .enablePlugins(ScalaJSWeb, ScalaJSBundlerPlugin)

onLoad in Global := (onLoad in Global).value andThen {s: State => "project js" :: s}